services:
  lobster:
    build: .
    container_name: lobster
    ports:
      - "8080:8080"
      - "443:443"
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s