services:
  lobster:
    build:
      context: .
      args:
        ZIP_FILE: bridge-test.zip #change this to your file version
    container_name: lobster
    ports:
      - "443:443"
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/bridge"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s